server:
  port: 8081

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: api-route
          uri: http://localhost:9999
          predicates:
            - Path=/proxy/api/**
          filters:
            - RewritePath=/proxy/api/(?<segment>.*), /${segment}

        - id: websocket-route
          uri: http://localhost:9999
          predicates:
            - Path=/proxy/ws/**
          filters:
            - RewritePath=/proxy/ws/(?<segment>.*), /${segment}
