server:
  port: 8081

# Swagger aggregator in GCP
springdoc:
  override-with-gateway-url: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: testing-service
        url: /proxy/v3/api-docs

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: api-route
          uri: http://testing-service
          predicates:
            - Path=/proxy/**
          filters:
            - RewritePath=/proxy/(?<segment>.*), /${segment}

        - id: websocket-route
          uri: http://testing-service
          predicates:
            - Path=/proxy/ws/**
          filters:
            - RewritePath=/proxy/ws/(?<segment>.*), /${segment}
